import test from 'node:test';
import assert from 'node:assert/strict';
import {createMaze,centerOf,canOccupy,pathTo} from '../src/maze.js';
import {createGame,startGame,updateGame,interact,blocksFor,actorPosition,gameSnapshot} from '../src/game.js';
import {GAME_CONFIG as C,addEvidence} from '../src/game-config.js';
import {fireGun,attackPlayer} from '../src/combat.js';
import {hiddenInput} from '../src/hiding.js';
import {placeInCorn} from './helpers/scenarios.mjs';
import {senseZombie,updateZombie,choosePrediction,predictionCandidates} from '../src/zombie-ai.js';
import {updateFeedback} from '../src/threat-director.js';
const maze=createMaze(),dt=1/60;
function game(){const g=createGame(maze);startGame(g);g.doorOpen=true;g.entered=true;g.player.flashlightOn=false;Object.assign(g.player,centerOf(3,20));Object.assign(g.enemy,{...centerOf(3,18),yaw:Math.PI,visible:true});return g;}
function hidden(){const g=game();Object.assign(g.enemy,centerOf(29,3));return placeInCorn(g);}
test('valid aimed shot spends a round and staggers without enemy health',()=>{const g=game();assert.equal(fireGun(g,[]),true);assert.equal(g.player.ammo,1);assert.equal(g.enemy.state,'staggered');assert.equal(g.enemy.health,undefined);});
test('miss spends a round and emits exact gunshot evidence',()=>{const g=game();g.player.yaw=Math.PI;assert.equal(fireGun(g,[]),false);assert.equal(g.player.ammo,1);assert.equal(g.evidence[0].type,'gunshot');assert.deepEqual(g.evidence[0].position,{x:g.player.x,z:g.player.z});});
test('zero ammunition does not fire',()=>{const g=game();g.player.ammo=0;fireGun(g,[]);assert.equal(g.metrics.shotsFired,0);assert.equal(g.player.ammo,0);});
test('shot cooldown prevents repeated simultaneous rounds',()=>{const g=game();fireGun(g,[]);fireGun(g,[]);assert.equal(g.metrics.shotsFired,1);});
test('pitch above gameplay capsule misses',()=>{const g=game();g.player.pitch=1;assert.equal(fireGun(g,[]),false);});
test('gun cannot hit through walls',()=>{const g=game();Object.assign(g.enemy,centerOf(7,20));g.player.yaw=-Math.PI/2;assert.equal(fireGun(g,[]),false);});
test('gun max range is enforced',()=>{const g=game();Object.assign(g.enemy,centerOf(3,3));assert.equal(fireGun(g,[]),false);});
test('repeated valid shot events never kill or remove the zombie',()=>{const g=game();for(let i=0;i<5;i++){g.player.ammo=1;g.player.shotCooldown=0;g.player.pitch=Math.atan2((i?.5:1.25)-C.player.eyeHeight,Math.hypot(g.enemy.x-g.player.x,g.enemy.z-g.player.z));assert.equal(fireGun(g,[]),true);assert.equal(g.enemy.visible,true);}assert.equal(g.metrics.shotsHit,5);});
test('one second catch-up consumes fire and F once',()=>{const g=game();updateGame(g,1,{fire:true,flashlight:true});assert.equal(g.metrics.shotsFired,1);assert.equal(g.player.flashlightOn,true);});
test('contact windup commits one tackle without immediate damage',()=>{const g=game();Object.assign(g.enemy,{...g.player,state:'chase'});attackPlayer(g,[]);g.elapsed+=.23;attackPlayer(g,[]);attackPlayer(g,[]);assert.equal(g.player.health,100);assert.equal(g.metrics.hitsTaken,1);assert.equal(g.interaction.phase,'tackle');});
test('an unanswered tackle drains health to zero and ends the run',()=>{const g=game();Object.assign(g.enemy,{...centerOf(3,20),state:'chase',yaw:0});attackPlayer(g,[]);g.elapsed+=.23;attackPlayer(g,[]);updateGame(g,3.6);assert.equal(g.player.health,0);assert.equal(g.mode,'dead');});
test('ordinary wounded movement remains free and health does not regenerate',()=>{const g=game();g.player.health=66;g.enemy.state='staggered';g.enemy.timer=3;const z=g.player.z;updateGame(g,.3,{forward:1});assert.ok(g.player.z<z);assert.equal(g.player.health,66);});
test('walls prevent attacks even at short geometric range',()=>{const g=game();g.player.x=4*2.35-.26;g.player.z=20.5*2.35;Object.assign(g.enemy,{x:4*2.35+.26,z:g.player.z,state:'chase'});assert.equal(attackPlayer(g,[]),false);});
test('checkpoint one restores health, grants ammo once, and increments tier',()=>{const g=game();Object.assign(g.player,maze.checkpoints[0]);g.player.health=12;updateGame(g,dt);assert.equal(g.player.health,100);assert.equal(g.player.ammo,4);assert.equal(g.progress.escalationTier,1);updateGame(g,1);assert.equal(g.player.ammo,4);});
test('checkpoint two caps ammunition and rewards only once',()=>{const g=game();g.progress.checkpointIndex=1;g.progress.escalationTier=1;g.progress.activatedCheckpoints=['cross'];g.player.ammo=5;Object.assign(g.player,maze.checkpoints[1]);updateGame(g,dt);assert.equal(g.player.ammo,6);assert.equal(g.progress.escalationTier,2);updateGame(g,dt);assert.equal(g.player.ammo,6);});
test('checkpoint fairness beats simultaneous rage attack',()=>{const g=game();Object.assign(g.player,maze.checkpoints[0]);Object.assign(g.enemy,{...g.player,state:'rage_chase'});g.player.health=5;updateGame(g,dt);assert.equal(g.player.health,100);assert.equal(g.enemy.state,'disengage');assert.ok(g.grace>0);});
test('daughter success takes precedence over simultaneous damage',()=>{const g=game();Object.assign(g.player,maze.daughter);Object.assign(g.enemy,{...g.player,state:'chase'});g.player.health=1;updateGame(g,dt);assert.equal(g.mode,'won');assert.equal(g.player.health,1);assert.equal(g.gateClosed,false);});
test('legacy white-light exit is not a success requirement',()=>{const g=game();Object.assign(g.player,maze.exit);updateGame(g,dt);assert.equal(g.mode,'playing');Object.assign(g.player,maze.daughter);updateGame(g,dt);assert.equal(g.mode,'won');});
test('beam outside cone never produces recoil',()=>{const g=game();g.player.flashlightOn=true;g.player.yaw=Math.PI;updateGame(g,.3);assert.notEqual(g.enemy.state,'flashlight_recoil');});
test('confirmed beam causes recoil before rage',()=>{const g=game();g.player.flashlightOn=true;updateGame(g,.25);assert.equal(g.enemy.state,'flashlight_recoil');updateGame(g,.7);assert.equal(g.enemy.state,'rage_chase');});
test('beam origin gives facing-away recoil and rage a real pursuit target',()=>{const g=game();g.player.flashlightOn=true;g.enemy.yaw=0;g.enemy.state='observe';g.enemy.timer=5;assert.equal(g.enemy.memory.lastKnown,null);updateGame(g,.25);assert.equal(g.enemy.perception.seen,false);assert.equal(g.enemy.state,'flashlight_recoil');assert.deepEqual(g.enemy.memory.lastBeam,{x:g.player.x,z:g.player.z});updateGame(g,.7);assert.equal(g.enemy.state,'rage_chase');assert.ok(g.enemy.target);const before=g.enemy.z;updateGame(g,.3);assert.ok(g.enemy.z>before);});
test('hidden flashlight without an exposed beam does not create beam-origin knowledge',()=>{const g=hidden();g.player.flashlightOn=true;senseZombie(g,[]);assert.equal(g.enemy.perception.beam,false);assert.equal(g.enemy.memory.lastBeam,undefined);assert.equal(g.enemy.memory.lastKnown,null);});
test('shot interrupts rage with stagger',()=>{const g=game();g.enemy.state='rage_chase';g.player.pitch=Math.atan2(.8-C.player.eyeHeight,4.7);fireGun(g,[]);assert.equal(g.enemy.state,'staggered');});
test('rage has no arbitrary duration expiry',()=>{const g=game();g.enemy.state='rage_chase';g.enemy.timer=0;g.enemy.memory.lastKnown=null;Object.assign(g.player,centerOf(7,20));updateZombie(g,12,[]);assert.equal(g.enemy.state,'rage_chase');});
test('far no-LOS hold ends rage, single lost frame does not',()=>{const g=game();g.enemy.state='rage_chase';Object.assign(g.player,centerOf(29,25));updateZombie(g,dt,[]);assert.equal(g.enemy.state,'rage_chase');updateZombie(g,2.1,[]);assert.equal(g.enemy.state,'disengage');});
// Physical entry/exit, local hearing, shared collision and gate coverage live in corn-world.test.mjs.
test('silent corn does not disclose its position to a remote enemy',()=>{const g=hidden();updateGame(g,.2);assert.equal(g.player.hidden,true);assert.equal(g.enemy.memory.lastSeen,null);assert.equal(g.enemy.memory.lastKnown,null);});
test('subthreshold mouse jitter and unchanged yaw produce no rustle',()=>{const g=hidden();updateGame(g,.2,{lookDelta:.5,yaw:g.player.yaw});assert.equal(g.evidence.length,0);assert.equal(g.enemy.memory.lastKnown,null);});
test('silent stagger expiry cannot reveal an unseen corn position',()=>{const g=hidden();g.enemy.state='staggered';g.enemy.timer=.05;updateGame(g,.06);assert.equal(g.enemy.state,'investigate');assert.equal(g.enemy.memory.lastKnown,null);});
test('corn movement emits actual local coordinates without an occupancy identifier',()=>{const g=hidden();hiddenInput(g,{movementIntent:true});assert.equal(g.evidence[0].type,'rustle');assert.equal(g.evidence[0].anchorId,undefined);assert.deepEqual(g.evidence[0].position,{x:g.player.x,z:g.player.z});});
test('stillness preserves location while active time continues',()=>{const g=hidden(),p={x:g.player.x,z:g.player.z};updateGame(g,1);assert.ok(g.elapsed>=1);assert.deepEqual({x:g.player.x,z:g.player.z},p);});
test('tier one can withdraw once then resume evidence-based search',()=>{const g=hidden();g.progress.escalationTier=1;g.enemy.state='predictive_search';g.enemy.searchCells=[];g.enemy.memory.lastKnown=centerOf(29,5);updateZombie(g,dt,[]);assert.equal(g.enemy.reason,'false_withdrawal');assert.equal(g.enemy.state,'disengage');for(let i=0;i<90;i++)updateZombie(g,dt,[]);assert.equal(g.enemy.state,'predictive_search');assert.equal(g.enemy.falseWithdrawalDone,true);});
test('loss of vision goes through search before stalking',()=>{const g=game();g.enemy.state='chase';g.enemy.target={...g.player};g.enemy.memory.lastKnown={...g.player};Object.assign(g.player,centerOf(7,20));updateGame(g,1.5);assert.equal(g.enemy.state,'predictive_search');});
test('prediction chooses a reachable bounded candidate',()=>{const g=game();g.enemy.memory.lastKnown=centerOf(3,20);const target=choosePrediction(g,[]);assert.ok(pathTo(maze,g.enemy,target).length);assert.ok(predictionCandidates(g,[]).length<=24);});
test('prediction uses heading evidence and records its reason',()=>{const g=game();g.enemy.memory.lastKnown=centerOf(3,20);g.enemy.memory.lastKnownHeading={x:0,z:-1};choosePrediction(g,[]);assert.equal(g.enemy.reason,'heading_and_route');});
test('predictor is invariant to unseen hidden coordinates and camera',()=>{const a=hidden(),b=hidden();a.enemy.memory.lastKnown=b.enemy.memory.lastKnown=centerOf(3,20);b.player.x=65;b.player.z=5;b.player.yaw=2;b.player.hideAnchorId='hide-6';assert.deepEqual(choosePrediction(a,[]),choosePrediction(b,[]));});
test('remembered view informs prediction after current visual contact is lost',()=>{const g=game();senseZombie(g,[]);const view=structuredClone(g.enemy.memory.viewObservation);Object.assign(g.player,centerOf(7,20));g.player.yaw=2;g.player.flashlightOn=true;senseZombie(g,[]);assert.equal(g.enemy.perception.seen,false);assert.deepEqual(g.enemy.memory.viewObservation,view);choosePrediction(g,[]);assert.equal(g.enemy.predictionViewAt,view.at);});
test('view-memory prediction is invariant to hidden current view and light switches',()=>{const a=hidden(),b=hidden(),observed={position:centerOf(3,23),yaw:0,flashlightOn:true,at:0};for(const g of [a,b]){g.enemy.memory.lastKnown=centerOf(3,23);g.enemy.memory.viewObservation=structuredClone(observed);}b.player.x=65;b.player.z=5;b.player.yaw=Math.PI;b.player.flashlightOn=true;b.player.hideAnchorId='hide-6';assert.deepEqual(choosePrediction(a,[]),choosePrediction(b,[]));assert.equal(a.enemy.predictionViewAt,0);});
test('remembered facing direction changes seeded side/rear target selection',()=>{const a=hidden(),b=hidden();for(const g of [a,b]){g.enemy.memory.lastKnown=centerOf(3,23);g.progress.escalationTier=1;g.threat.directorIntent='circle';g.enemy.memory.viewObservation={position:centerOf(3,23),yaw:0,flashlightOn:true,at:0};}b.enemy.memory.viewObservation.yaw=Math.PI;assert.notDeepEqual(choosePrediction(a,[]),choosePrediction(b,[]));});
test('expired view observation stops influencing prediction',()=>{const g=hidden();g.enemy.memory.viewObservation={position:centerOf(3,23),yaw:0,flashlightOn:true,at:0};g.elapsed=C.zombie.memorySeconds+1;choosePrediction(g,[]);assert.equal(g.enemy.predictionViewAt,null);});
test('different seeds permit plausible wrong branches',()=>{const selected=new Set();for(let seed=1;seed<9;seed++){const g=game();g.enemy.rng=seed;g.enemy.memory.lastKnown=centerOf(3,23);selected.add(JSON.stringify(choosePrediction(g,[])));}assert.ok(selected.size>1);});
test('search visits multiple cells before abandoning evidence',()=>{const g=hidden();Object.assign(g.enemy,{...centerOf(3,20),state:'predictive_search',searchCells:[centerOf(3,20),centerOf(3,21),centerOf(3,20)],searchVisited:0});for(let i=0;i<600&&g.enemy.state==='predictive_search';i++)updateZombie(g,dt,[]);assert.ok(g.enemy.searchVisited>=3);assert.ok(g.metrics.searchCellsVisited>=3);});
test('evidence is consumed once and memory expires into uncertainty',()=>{const g=hidden();addEvidence(g,'gunshot',g.enemy,60,4);senseZombie(g,[]);assert.equal(g.evidence.length,0);assert.equal(g.enemy.perception.heard,true);g.elapsed=20;senseZombie(g,[]);assert.equal(g.enemy.perception.heard,false);assert.equal(g.enemy.memory.lastKnown,null);});
test('far proximity raises music without threat text',()=>{const g=game();g.enemy.x=g.player.x+17;updateFeedback(g,dt);assert.equal(g.threat.proximityTier,1);assert.ok(g.threat.intensity>0);assert.equal(g.threat.activeMessage,null);});
test('behind warning requires actual close rear angle',()=>{const g=game();Object.assign(g.enemy,{x:g.player.x,z:g.player.z+2});updateFeedback(g,dt);assert.equal(g.threat.activeMessage,"IT'S RIGHT BEHIND YOU");g.threat.lastMessageAt=-10;g.enemy.z=g.player.z-2;updateFeedback(g,dt);assert.notEqual(g.threat.activeMessage,"IT'S RIGHT BEHIND YOU");});
test('can-see-you warning requires current visual perception',()=>{const g=game();g.enemy.z=g.player.z-4;g.enemy.perception.seen=false;updateFeedback(g,dt);assert.notEqual(g.threat.activeMessage,'IT CAN SEE YOU');g.enemy.perception.seen=true;g.threat.lastMessageAt=-10;updateFeedback(g,dt);assert.equal(g.threat.activeMessage,'IT CAN SEE YOU');});
test('message cooldown prevents consecutive warning spam',()=>{const g=game();g.enemy.z=g.player.z-4;updateFeedback(g,dt);updateFeedback(g,dt);assert.equal(g.events.filter(e=>e.type==='threat').length,1);});
test('at most two threat cards appear in ten seconds with a short flash',()=>{const g=game();g.enemy.z=g.player.z-4;for(const at of [0,4.6,9.2]){g.elapsed=at;updateFeedback(g,dt);}assert.equal(g.events.filter(e=>e.type==='threat').length,2);assert.ok(g.threat.activeMessageTime<=C.feedback.normalFlashSeconds);});
test('rear warnings do not falsely describe threats through corn walls',()=>{const g=game();g.player.yaw=Math.PI/2;g.enemy.x=g.player.x+3;g.enemy.z=g.player.z;updateFeedback(g,dt);assert.notEqual(g.threat.activeMessage,"IT'S RIGHT BEHIND YOU");assert.notEqual(g.threat.activeMessage,'DO NOT TURN AROUND');});
test('fresh run state is independent of a previously mutated run', () => {
  const previous = hidden();
  previous.player.ammo = 0;
  previous.player.health = 2;
  previous.progress.activatedCheckpoints.push('cross');
  previous.enemy.memory.lastSeen = { x: 1, z: 2 };
  previous.metrics.shotsFired = 9;
  const before = gameSnapshot(previous);
  const fresh = createGame(maze);
  assert.equal(fresh.player.ammo, 2);
  assert.equal(fresh.player.health, 100);
  assert.equal(fresh.player.hidden, false);
  assert.equal(fresh.enemy.memory.lastSeen, null);
  assert.equal(fresh.metrics.shotsFired, 0);
  assert.deepEqual(fresh.progress.activatedCheckpoints, []);
  fresh.progress.activatedCheckpoints.push('barrels');
  assert.deepEqual(gameSnapshot(previous), before);
});
