import test from 'node:test';import assert from 'node:assert/strict';import {deflateSync} from 'node:zlib';import {createHash,webcrypto} from 'node:crypto';
import {createVisualCheckAPI,LIMITS,validatePNG} from '../worker/visual-check-worker.js';
globalThis.crypto??=webcrypto;
const origin='https://private-game.example';
class MockR2{map=new Map();async put(key,value,options={}){if(options.onlyIf?.get?.('If-None-Match')==='*'&&this.map.has(key))return null;const headerMatch=options.onlyIf?.get?.('If-Match');if(headerMatch&&headerMatch!=='*'&&!/^\"[^\"]+\"$/.test(headerMatch))throw new TypeError('Invalid ETag in if-match header');if(headerMatch&&headerMatch!=='*'&&headerMatch.slice(1,-1)!==this.map.get(key)?.etag)return null;if(options.onlyIf?.etagMatches&&options.onlyIf.etagMatches!==this.map.get(key)?.etag)return null;const bytes=typeof value==='string'?new TextEncoder().encode(value):new Uint8Array(value);const o={key,bytes,size:bytes.length,httpMetadata:options.httpMetadata||{},customMetadata:options.customMetadata||{},etag:createHash('sha256').update(bytes).digest('hex')};this.map.set(key,o);return o;}async get(k){const o=this.map.get(k);return o?{...o,body:o.bytes,json:async()=>JSON.parse(new TextDecoder().decode(o.bytes))}:null;}async head(k){return this.map.get(k)||null;}async list({prefix,limit}){const objects=[...this.map.values()].filter(x=>x.key.startsWith(prefix)).slice(0,limit);return {objects,truncated:false};}}
const run=()=>({id:crypto.randomUUID(),game:'cornfields',release:'abc123',purpose:'game-visual-check',quality:'balanced',viewport:{width:1280,height:720,dpr:1},browser:{family:'Chrome',version:'130',platform:'macOS',webgl:'WebGL2'},seed:7321,scenes:['driving-steering-grips']});
const metrics=()=>({scene:'driving-steering-grips',width:1,height:1,phase:'render-only',samples:[[700,'cold'],[16.7,'transition'],[900,'steady'],[2500,'hidden'],[16.7,'steady']],assets:{status:'ready',items:[{name:'car',status:'ready'}]},render:{calls:100,triangles:2000,quality:'balanced'},captureMs:.3,encodingMs:15});
function fixture(){const bucket=new MockR2(),handler=createVisualCheckAPI({game:'cornfields',release:'abc123',ownerPrivate:true,limits:{runsPerDay:4,runsPerHour:20}});return {bucket,async request(path,method='GET',data=null,headers={}){const type=data instanceof Uint8Array?'image/png':'application/json';return handler(new Request(origin+'/api/visual-check/'+path,{method,headers:{'Origin':origin,...(method==='GET'?{}:{'X-Visual-Check':'1','Content-Type':type}),...headers},body:data===null?undefined:data instanceof Uint8Array?data:JSON.stringify(data)}),{CAPTURES:bucket});}};}
const crc=a=>{let c=-1;for(const n of a){c^=n;for(let i=0;i<8;i++)c=(c>>>1)^((c&1)?0xedb88320:0);}return (c^-1)>>>0;};
function chunk(name,data){const out=new Uint8Array(12+data.length),d=new DataView(out.buffer);d.setUint32(0,data.length);out.set(new TextEncoder().encode(name),4);out.set(data,8);d.setUint32(8+data.length,crc(out.subarray(4,8+data.length)));return out;}
function png({w=1,h=1,extra=false}={}){const head=new Uint8Array(13),v=new DataView(head.buffer);v.setUint32(0,w);v.setUint32(4,h);head[8]=8;head[9]=6;const a=[new Uint8Array([137,80,78,71,13,10,26,10]),chunk('IHDR',head),...(extra?[chunk('tEXt',new TextEncoder().encode('not retained'))]:[]),chunk('IDAT',deflateSync(new Uint8Array([0,255,0,0,255]))),chunk('IEND',new Uint8Array())];return new Uint8Array(Buffer.concat(a));}
test('private deployment precondition is explicit',()=>assert.throws(()=>createVisualCheckAPI({game:'cornfields',release:'abc123'}),/owner-private/));
test('complete mocked R2 lifecycle with idempotent retry, image read, metrics, listing',async()=>{const f=fixture(),r=run();assert.equal((await f.request('runs','POST',r)).status,201);assert.equal((await f.request('runs','POST',r)).status,200);assert.equal((await f.request(`runs/${r.id}/result`,'POST',{status:'complete'})).status,409);assert.equal((await f.request(`runs/${r.id}/frames/0.png`,'PUT',png())).status,201);assert.equal((await f.request(`runs/${r.id}/frames/0.png`,'PUT',png())).status,200);assert.equal((await f.request(`runs/${r.id}/frames/0`,'POST',metrics())).status,200);assert.equal((await f.request(`runs/${r.id}/result`,'POST',{status:'complete'})).status,200);const read=await f.request(`runs/${r.id}`),body=await read.json();assert.equal(body.frames.length,1);assert.deepEqual(body.frames[0].metrics.samples,metrics().samples);assert.equal(body.result.status,'complete');const image=await f.request(`runs/${r.id}/frames/0.png`);assert.equal(image.headers.get('content-type'),'image/png');assert.equal(image.headers.get('access-control-allow-origin'),null);assert.equal(image.headers.get('cache-control'),'private, no-store');assert.deepEqual(new Uint8Array(await image.arrayBuffer()),png());assert.equal((await (await f.request('runs')).json()).runs.length,1);});
test('reject cross-site requests and missing custom write header',async()=>{const f=fixture();assert.equal((await f.request('runs','POST',run(),{Origin:'https://evil.example'})).status,403);assert.equal((await f.request('runs','POST',run(),{'X-Visual-Check':''})).status,403);assert.equal((await f.request('runs','GET',null,{'Sec-Fetch-Site':'cross-site'})).status,403);});
test('strict metadata allowlist never accepts arbitrary DOM, alias, storage or URLs',async()=>{for(const field of ['alias','html','localStorage','cookies','url','email']){const f=fixture();assert.equal((await f.request('runs','POST',{...run(),[field]:'private'})).status,400);assert.equal(f.bucket.map.size,0);}});
test('reject mismatched build and site game',async()=>{for(const change of [{release:'old'},{game:'other'}])assert.equal((await fixture().request('runs','POST',{...run(),...change})).status,409);});
test('safe IDs and maximum scene counts',async()=>{assert.equal((await fixture().request('runs','POST',{...run(),id:'../../other'})).status,409);assert.equal((await fixture().request('runs','POST',{...run(),scenes:Array.from({length:13},(_,i)=>'scene-'+i)})).status,400);assert.equal((await fixture().request('runs','POST',{...run(),scenes:['../../secret']})).status,400);});
test('daily cap is enforced with concurrent requests',async()=>{const f=fixture();const results=await Promise.all(Array.from({length:10},()=>f.request('runs','POST',run())));assert.equal(results.filter(r=>r.status===201).length,4);assert.equal(results.filter(r=>r.status===429).length,6);});
test('PNG framing, dimensions, size and metadata stripping',()=>{assert.equal(validatePNG(png()).width,1);assert.deepEqual(validatePNG(png({extra:true})).bytes,png());assert.throws(()=>validatePNG(new Uint8Array([1,2,3])));assert.throws(()=>validatePNG(png({w:5000})));assert.throws(()=>validatePNG(png().slice(0,-1)));assert.throws(()=>validatePNG(new Uint8Array(LIMITS.pngBytes+1)));});
test('invalid image and metrics never replace an existing frame',async()=>{const f=fixture(),r=run();await f.request('runs','POST',r);assert.equal((await f.request(`runs/${r.id}/frames/1.png`,'PUT',png())).status,404);assert.equal((await f.request(`runs/${r.id}/frames/0`,'POST',metrics())).status,409);assert.equal((await f.request(`runs/${r.id}/frames/0.png`,'PUT',new Uint8Array([1,2,3]))).status,400);await f.request(`runs/${r.id}/frames/0.png`,'PUT',png());assert.equal((await f.request(`runs/${r.id}/frames/0`,'POST',{...metrics(),width:2})).status,400);assert.equal((await f.request(`runs/${r.id}/frames/0`,'POST',{...metrics(),arbitraryText:'no'})).status,400);assert.equal((await f.request(`runs/${r.id}/frames/0`,'POST',{...metrics(),samples:[[1001,'discarded']]})).status,400);});
test('missing R2 binding and storage failure produce safe clear errors',async()=>{const h=createVisualCheckAPI({game:'cornfields',release:'abc123',ownerPrivate:true});const response=await h(new Request(origin+'/api/visual-check/config'),{});assert.equal(response.status,503);assert.equal((await response.json()).error,'Private screenshot storage is not ready.');});
test('non-API paths belong to production static routing',async()=>{const h=createVisualCheckAPI({game:'cornfields',release:'abc123',ownerPrivate:true});assert.equal(await h(new Request(origin+'/assets/car.glb'),{}),null);});

test('per-game scene and synthetic-purpose allowlists are enforced',async()=>{const f=fixture();assert.equal((await f.request('runs','POST',{...run(),scenes:['made-up-safe-name']})).status,400);assert.equal((await f.request('runs','POST',{...run(),scenes:['chapter-approval']})).status,400);assert.equal((await f.request('runs','POST',{...run(),scenes:['synthetic-backend-probe']})).status,400);const r={...run(),purpose:'synthetic-storage-probe',scenes:['synthetic-backend-probe']};assert.equal((await f.request('runs','POST',r)).status,201);assert.equal((await f.request('runs','POST',{...run(),purpose:'synthetic-storage-probe'})).status,400);});

test('serial multi-image uploads release their per-run R2 lease',async()=>{const f=fixture(),r={...run(),scenes:['driving-steering-grips','turning-steering-grips']};assert.equal((await f.request('runs','POST',r)).status,201);assert.equal((await f.request(`runs/${r.id}/frames/0.png`,'PUT',png())).status,201);assert.equal((await f.request(`runs/${r.id}/frames/1.png`,'PUT',png())).status,201);const lock=await f.bucket.get(`visual-check/v1/runs/${r.id}/upload-lock.json`);assert.equal((await lock.json()).until,0);});
