#!/usr/bin/env python3
"""Offline playtest voice preparation. Requires installed Piper, ONNX Runtime and ffmpeg.

The model and all WAV intermediates stay outside the public runtime. No downloads,
service calls, installations or browser synthesis are performed by this script.
"""
import argparse
import hashlib
import json
from pathlib import Path
import subprocess
import time
import wave

import onnxruntime
from piper.voice import PiperVoice
from piper.config import PiperConfig, SynthesisConfig

parser = argparse.ArgumentParser()
parser.add_argument('--model', type=Path, required=True)
parser.add_argument('--config', type=Path, required=True)
parser.add_argument('--script', type=Path, required=True)
parser.add_argument('--scratch', type=Path, required=True)
parser.add_argument('--output', type=Path, default=Path('assets/audio/prologue'))
parser.add_argument('--manifest-only', action='store_true', help='Rebuild metadata from existing outputs and generated timings')
parser.add_argument('--timing-output', type=Path, default=Path('src/prologue-voice-timing.js'))
parser.add_argument('--timing-export', default='PROLOGUE_VOICE_TIMING')
parser.add_argument('--story', default='Jacob Nangle; approved fast interactive adaptation with retained/adapted/new/user cue provenance')
args = parser.parse_args()
started = time.monotonic()
config = json.loads(args.config.read_text())
options = onnxruntime.SessionOptions()
options.intra_op_num_threads = 2
options.inter_op_num_threads = 1
voice = None if args.manifest_only else PiperVoice(session=onnxruntime.InferenceSession(str(args.model), sess_options=options, providers=['CPUExecutionProvider']), config=PiperConfig.from_dict(config))
# Different pretrained corpus voices, never cloning a user or requested individual.
cast = {'mike': '5918', 'clarence': '3370', 'stanley': '5914', 'dispatch': '783', 'face': '783', 'unknown': '5914'}
timings = {}
args.output.mkdir(parents=True, exist_ok=True)
args.scratch.mkdir(parents=True, exist_ok=True)
lines = json.loads(args.script.read_text())
for line in lines:
    if time.monotonic() - started > 165:
        raise TimeoutError('Bounded voice preparation exceeded 165 seconds')
    speaker = config['speaker_id_map'][cast[line['voice']]]
    dest = args.output / (line['id'] + '.mp3')
    if args.manifest_only:
        duration = float(subprocess.check_output(['ffprobe', '-v', 'error', '-show_entries', 'format=duration', '-of', 'default=nw=1:nk=1', str(dest)], timeout=5))
        timings[line['id']] = {'duration': round(duration, 4)}
        continue
    wav = args.scratch / (line['id'] + '.wav')
    with wave.open(str(wav), 'wb') as stream:
        voice.synthesize_wav(line['text'], stream, SynthesisConfig(speaker_id=speaker, length_scale=1.03, noise_scale=.5, noise_w_scale=.65))
    # Natural delivery only. Timeline follows the measured clip; never speed up
    # a voice to fit an authored scene budget. Shorten the script if necessary.
    subprocess.run(['ffmpeg', '-nostdin', '-loglevel', 'error', '-y', '-threads', '1', '-i', str(wav), '-af', 'loudnorm=I=-19:TP=-2:LRA=9', '-ar', '24000', '-ac', '1', '-b:a', '56k', str(dest)], check=True, timeout=12)
    duration = float(subprocess.check_output(['ffprobe', '-v', 'error', '-show_entries', 'format=duration', '-of', 'default=nw=1:nk=1', str(dest)], timeout=5))
    timings[line['id']] = {'duration': round(duration, 4)}
    wav.unlink()
    print(line['id'], timings[line['id']]['duration'], flush=True)
args.timing_output.write_text('// Generated by scripts/build-prologue-voices.py; seconds per prerecorded utterance.\nexport const ' + args.timing_export + ' = Object.freeze(' + json.dumps(timings, indent=2) + ');\n')
manifest = {
    'type': 'temporary synthetic playtest dialogue', 'story': args.story,
    'generator': 'Installed Piper, offline ONNX CPU, two intra-op threads',
    'model': 'en_US-libritts_r-medium',
    'model_url': 'https://huggingface.co/rhasspy/piper-voices/tree/main/en/en_US/libritts_r/medium',
    'model_card': 'https://huggingface.co/rhasspy/piper-voices/blob/main/en/en_US/libritts_r/medium/MODEL_CARD',
    'model_sha256': hashlib.sha256(args.model.read_bytes()).hexdigest(),
    'license': 'CC BY 4.0 per model card; attribution and modified-output notice in LICENSES.md',
    'cast_corpus_ids': cast, 'voice_selection_reference': 'https://github.com/line/LibriTTS-P',
    'modifications': 'New scripted speech; gain normalization and mono MP3 encoding at natural delivery speed. Radio, face and unidentified-voice filtering applied at runtime.',
    'files': {p.name: {'bytes': p.stat().st_size, 'sha256': hashlib.sha256(p.read_bytes()).hexdigest(), **timings[p.stem]} for p in [args.output / (line['id'] + '.mp3') for line in lines]},
}
(args.output / 'sources.json').write_text(json.dumps(manifest, indent=2) + '\n')
print('Complete:', len(timings), 'utterances,', round(time.monotonic() - started, 2), 'seconds')
